#
# Production server with UWSGI configured to run on port 8080
# and web configured to run directly on port 80
#
# docker-compose build
# docker-compose up -d web
#
# See accompanying Make commands for easy collectstatic etc.

version: '3.7'
volumes:
  postgres-data:
  geoserver-datadir:
  rabbitmq:
  static-data:
  media-data:
  geocontext-scheduler-data:
x-common-django:
  &default-common-django
  image: bims_uwsgi:latest
  build:
    context: ../
    dockerfile: deployment/docker/Dockerfile
  command: uwsgi --ini /home/web/django_project/uwsgi.ini
  hostname: uwsgi
  working_dir: /home/web/django_project
  environment:
    - ADMIN_EMAILS=${ADMIN_EMAILS:-tetobobo1@gmail.com}
    - APP_NAME=bims
    - ASYNC_SIGNALS=True
    - BROKER_URL=amqp://rabbitmq:5672
    - C_FORCE_ROOT=1
    - CONTACT_US_EMAIL=${ADMIN_EMAILS:-tetobobo1@gmail.com}
    - ALLOWED_HOSTS=['41.222.246.28','rbis.ur.ac.rw','geoserver.rbis.ur.ac.rw','localhost']
    - DATABASE_HOST=db
    - DATABASE_NAME=${POSTGRES_DBNAME:-gis}
    - DATABASE_PASSWORD=${POSTGRES_PASS:-docker}
    - DATABASE_URL=postgis://${POSTGRES_USER:-docker}:${POSTGRES_PASS:-docker}@db:5432/${POSTGRES_DBNAME:-gis}
    - DATABASE_USERNAME=${POSTGRES_USER:-docker}
    - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
    - GEOCONTEXT_URL=${GEOCONTEXT_URL:-https://geocontext.kartoza.com}
    - GEOSERVER_LOCATION=http://localhost:5100/geoserver
    - GEOSERVER_LOCATION_SITE_LAYER=bims:location_site_view
    - GEOSERVER_PUBLIC_LOCATION=http://localhost:5100/geoserver
    - GEOSERVER_ADMIN_USER=${GEOSERVER_USERNAME:-admin}
    - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_PASSWORD:-admingeoserver}
    - MEDIA_ROOT=/home/web/media
    - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
    - ROOT_URLCONF=core.urls
    - SITEURL=https://rbis.ur.ac.rw/
    - STATIC_ROOT=/home/web/static/static
    - VIRTUAL_HOST=bims.kartoza.com
    - VIRTUAL_PORT=8080
  volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
    - /opt/bims/logs:/var/log/
  depends_on:
    - db
    - geoserver
    - rabbitmq
    - cache
  restart: unless-stopped
  user: root

services:

  db:
    container_name: bims_prod_db
    image: kartoza/postgis:11.5-2.5
    ports:
      - "5200:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DBNAME=${POSTGRES_DBNAME:-gis}
      - POSTGRES_USER=${POSTGRES_USER:-docker}
      - POSTGRES_PASS=${POSTGRES_PASS:-docker}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  geoserver:
    container_name: bims_prod_geoserver
    image: kartoza/geoserver:2.19.0
    ports:
      - "5100:8080"
    restart: unless-stopped
    environment:
      HTTP_HOST: ${HTTP_HOST:-0.0.0.0}
      HTTP_PORT: 8080
      GEOSERVER_ADMIN_USER: ${GEOSERVER_USERNAME:-admin}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASSWORD:-admingeoserver}
      DATABASE_URL: postgres://${POSTGRES_USER:-docker}:${POSTGRES_PASS:-docker}@db:5432/${POSTGRES_DBNAME:-gis}
    depends_on:
      - db
    volumes:
      - geoserver-datadir:/opt/geoserver/data_dir/

  uwsgi:
    <<: *default-common-django
    container_name: bims_prod_uwsgi
    ports:
      - "8080:8080"

  worker:
    <<: *default-common-django
    container_name: bims_prod_worker
    entrypoint: [ ]
    hostname: worker
    command: celery worker --app=bims.celery:app -Q update -B -l debug
    depends_on:
      - db
      - geoserver
      - rabbitmq
      - cache
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
      - ./logs:/var/log/

  geocontextworker:
    <<: *default-common-django
    container_name: bims_prod_geocontextworker
    entrypoint: [ ]
    hostname: worker
    command: celery worker --app=bims.celery:app --schedule /home/geocontext-scheduler/celerybeat-schedule -Q geocontext -B -l debug
    depends_on:
      - db
      - geoserver
      - rabbitmq
      - cache
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
      - ./logs:/var/log/
      - geocontext-scheduler-data:/home/geocontext-scheduler

  searchworker:
    <<: *default-common-django
    container_name: bims_prod_searchworker
    entrypoint: [ ]
    hostname: worker
    command: celery worker --app=bims.celery:app -Q search -B -l debug
    depends_on:
      - db
      - geoserver
      - rabbitmq
      - cache
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
      - ./logs:/var/log/

  dbbackups:
    container_name: bims_prod_dbbackups
    image: kartoza/pg-backup:9.6
    hostname: pg-backups
    depends_on:
      - db
    environment:
      - DUMPPREFIX=PG_bims
      - PGUSER=${POSTGRES_USER:-docker}
      - PGPASSWORD=${POSTGRES_PASS:-docker} 
      - PGPORT=5432
      - PGHOST=db
      - PGDATABASE=${POSTGRES_DBNAME:-gis}
    volumes:
      - /opt/bims/backups:/backups
    restart: unless-stopped

  # This is normally the main entry point for a production server
  rabbitmq:
    container_name: bims_prod_rabbitmq
    image: rabbitmq:3.7-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  cache:
   container_name: bims_prod_memcached
   image: memcached
   entrypoint:
    - memcached
    - -m 64

  gbif_ipt:
    container_name: bims_prod_gbif_ipt
    image: kartoza/gbif_ipt:latest
    depends_on:
      - db
    volumes:
      - /opt/bims/ipt:/usr/local/ip
    restart: unless-stopped