# Generated by Django 2.2.28 on 2025-09-17 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0329_auto_20250917_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversitythreat',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='biodiversity_threats_posters'),
        ),
    ]
