# Generated by Django 2.2.28 on 2025-09-21 20:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0330_auto_20250917_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodiversityAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content_title', ckeditor.fields.RichTextField()),
                ('main_doc_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biodiversity Assessment',
                'verbose_name_plural': 'Biodiversity Assessments',
                'ordering': ['created_at'],
            },
        ),
    ]
