# Generated by Django 2.2.28 on 2025-09-21 21:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0331_auto_20250921_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversityassessment',
            name='content_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
