# Generated by Django 2.2.28 on 2025-12-06 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0332_auto_20250921_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload species image', null=True, upload_to='taxonomy/images/', verbose_name='Species Image'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='more_info_url',
            field=models.URLField(blank=True, help_text='URL to additional information about the species', max_length=500, null=True, verbose_name='More Info URL'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='sound',
            field=models.FileField(blank=True, help_text='Upload species sound/audio file', null=True, upload_to='taxonomy/sounds/', verbose_name='Species Sound'),
        ),
    ]
