# Generated by Django 2.2.28 on 2025-12-06 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0333_auto_20251206_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularGeneticGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_genetic_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecular Genetic Group',
                'verbose_name_plural': 'Molecular Genetic Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MolecularGeneticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='molecular_genetics/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genetic_data', to='bims.MolecularGeneticGroup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_genetic_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecular Genetic Data',
                'verbose_name_plural': 'Molecular Genetic Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MolecularGeneticDownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting download')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_genetic_requests', to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='bims.MolecularGeneticData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genetic_download_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Request',
                'verbose_name_plural': 'Download Requests',
                'ordering': ['-created_at'],
                'unique_together': {('data', 'user')},
            },
        ),
    ]
